repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.2.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
        args: [--py37-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.0
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
        exclude: ^testing/resources/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        exclude: ^docs/conf.py
        additional_dependencies:
          - types-dataclasses >= 0.1.3
          - types-PyYAML
          - tomli >= 0.2.6, < 2.0.0
          - types-typed-ast >= 1.4.1
          - click >= 8.1.0
          - platformdirs >= 2.1.0
          - pytest
          - hypothesis

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude: \.github/workflows/diff_shades\.yml