{
 "title": "On-demand batch job demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Batch job count per status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_nomad_job_summary_queued{exported_job=~\"batch/.*\"}) OR on() vector(0)",
     "legendFormat": "queued"
    },
    {
     "expr": "sum(nomad_nomad_job_summary_running{exported_job=~\"batch/.*\"}) OR on() vector(0)",
     "legendFormat": "running"
    },
    {
     "expr": "sum(nomad_nomad_job_summary_complete{exported_job=~\"batch/.*\"}) OR on() vector(0)",
     "legendFormat": "complete"
    },
    {
     "expr": "sum(nomad_nomad_job_summary_failed{exported_job=~\"batch/.*\"}) OR on() vector(0)",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Clients per datacenter",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (datacenter) (nomad_client_uptime{node_status=\"ready\"})",
     "legendFormat": "{{datacenter}}"
    }
   ]
  },
  {
   "title": "Batch jobs in progress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(nomad_nomad_job_summary_running{exported_job=~\"batch/.*\"}) OR on() vector(0)",
     "legendFormat": "running"
    },
    {
     "expr": "sum(nomad_nomad_job_summary_queued{exported_job=~\"batch/.*\"}) OR on() vector(0)",
     "legendFormat": "queued"
    }
   ]
  },
  {
   "title": "Number of clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (datacenter) (nomad_client_uptime{node_status=\"ready\"})",
     "legendFormat": "{{datacenter}}"
    }
   ]
  }
 ]
}