name: lint

on: [push, pull_request]
jobs:
  pre-commit:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
      
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up latest Python
      uses: actions/setup-python@v4
      with:
        python-version: '*'

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          python -m pip install -e '.[d]'
          python -m pip install tox

    - name: Run pre-commit hooks
      uses: pre-commit/action@v3.0.0
    
    - name: Format ourselves
      run: |
          tox -e run_self