name: lint

on: [push, pull_request]
jobs:
  pre-commit:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up latest Python
      uses: actions/setup-python@v4
      with:
        python-version: '*'

    - name: Run pre-commit hooks
      uses: pre-commit/action@v3.0.0
      
    - name: pre-commit-ci/lite-action
      uses: pre-commit-ci/lite-action@v1.0.0
      if: always()